// !!!!!!!!!!!!!!!!!!!!!!!
// This file was generated by AI, to make tests mockable
// stm HAL is realy not test friendly library


#ifndef FAKE_HAL_H
#define FAKE_HAL_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

// ============================================================================
// GLOBAL FAKE STATE
// ============================================================================


/* Statusy HAL */
typedef enum {
    HAL_OK      = 0x00U,
    HAL_ERROR   = 0x01U,
    HAL_BUSY    = 0x02U,
    HAL_TIMEOUT = 0x03U
} HAL_StatusTypeDef;

/* GPIO Pin State */
typedef enum {
    GPIO_PIN_RESET = 0u,
    GPIO_PIN_SET   = 1u
} GPIO_PinState;

/* GPIO Typedef - pusta struktura dla symulacji */
typedef struct {
    uint32_t dummy;
} GPIO_TypeDef;

/* GPIO Init TypeDef */
typedef struct {
    uint32_t Pin;
    uint32_t Mode;
    uint32_t Pull;
    uint32_t Speed;
    uint32_t Alternate;
} GPIO_InitTypeDef;

/* TIM Handle TypeDef */
typedef struct {
    uint32_t Instance;
    uint32_t State;
    uint32_t Channel;
} TIM_HandleTypeDef;

/* TIM OC Init TypeDef */
typedef struct {
    uint32_t OCMode;
    uint32_t Pulse;
    uint32_t OCPolarity;
    uint32_t OCNPolarity;
    uint32_t OCFastMode;
    uint32_t OCIdleState;
    uint32_t OCNIdleState;
} TIM_OC_InitTypeDef;

/* TIM IC Init TypeDef */
typedef struct {
    uint32_t ICPolarity;
    uint32_t ICSelection;
    uint32_t ICPrescaler;
    uint32_t ICFilter;
} TIM_IC_InitTypeDef;

/* DMA Handle TypeDef */
typedef struct {
    uint32_t Instance;
    uint32_t State;
} DMA_HandleTypeDef;

/* PCD Handle TypeDef */
typedef struct {
    uint32_t Instance;
    uint32_t State;
} PCD_HandleTypeDef;

/* EXTI Handle TypeDef */
typedef struct {
    uint32_t Line;
    uint32_t Mode;
    uint32_t Trigger;
    uint32_t GPIOSel;
    uint32_t RTC_EventSel;
    uint32_t RisingTrigger;
    uint32_t FallingTrigger;
} EXTI_HandleTypeDef;

/* RCC Init TypeDef */
typedef struct {
    uint32_t OscillatorType;
    uint32_t HSEState;
    uint32_t LSEState;
    uint32_t HSIState;
    uint32_t HSICalibrationValue;
    uint32_t LSIState;
    uint32_t PLL;
} RCC_OscInitTypeDef;

typedef struct {
    uint32_t ClockType;
    uint32_t SYSCLKSource;
    uint32_t AHBCLKDivider;
    uint32_t APB1CLKDivider;
    uint32_t APB2CLKDivider;
} RCC_ClkInitTypeDef;

// ============================================================================
// DEFinicje STAŁYCH (symulowane)
// ============================================================================

/* TIM Channels */
#define TIM_CHANNEL_1      0u
#define TIM_CHANNEL_2      1u
#define TIM_CHANNEL_3      2u
#define TIM_CHANNEL_4      3u

/* GPIO Piny */
#define GPIO_PIN_0         ((uint16_t)0x0001)
#define GPIO_PIN_1         ((uint16_t)0x0002)
#define GPIO_PIN_2         ((uint16_t)0x0004)
#define GPIO_PIN_3         ((uint16_t)0x0008)
#define GPIO_PIN_4         ((uint16_t)0x0010)
#define GPIO_PIN_5         ((uint16_t)0x0020)
#define GPIO_PIN_6         ((uint16_t)0x0040)
#define GPIO_PIN_7         ((uint16_t)0x0080)
#define GPIO_PIN_8         ((uint16_t)0x0100)
#define GPIO_PIN_9         ((uint16_t)0x0200)
#define GPIO_PIN_10        ((uint16_t)0x0400)
#define GPIO_PIN_11        ((uint16_t)0x0800)
#define GPIO_PIN_12        ((uint16_t)0x1000)
#define GPIO_PIN_13        ((uint16_t)0x2000)
#define GPIO_PIN_14        ((uint16_t)0x4000)
#define GPIO_PIN_15        ((uint16_t)0x8000)

/* TIM Flags */
#define TIM_FLAG_UPDATE    (1u << 0)
#define TIM_FLAG_CC1       (1u << 1)
#define TIM_FLAG_CC2       (1u << 2)
#define TIM_FLAG_CC3       (1u << 3)
#define TIM_FLAG_CC4       (1u << 4)

/* DMA Flags */
#define DMA_FLAG_TC1       (1u << 0)
#define DMA_FLAG_HT1       (1u << 1)
#define DMA_FLAG_TE1       (1u << 2)
#define DMA_FLAG_FE1       (1u << 3)
#define DMA_FLAG_DME1      (1u << 4)


// RCC State
static uint32_t rcc_flags = 0;
static uint32_t rcc_it_status = 0;
static uint32_t rcc_it_source = 0;

// GPIO State
static uint16_t gpio_output_state = 0;
static uint16_t gpio_written_pin = 0;
static uint32_t gpio_exti_flags = 0;
static uint32_t gpio_exti_it_status = 0;
static uint32_t gpio_exti_enabled = 0;

// DMA State
static uint32_t dma_flags = 0;
static uint32_t dma_it_status = 0;
static uint32_t dma_it_source = 0;
static bool dma_transfer_complete = false;
static uint32_t dma_src_addr = 0;
static uint32_t dma_dst_addr = 0;
static uint32_t dma_data_length = 0;

// TIM State
static uint32_t tim_counter = 0;
static uint32_t tim_autoreload = 0xFFFF;
static uint32_t tim_prescaler = 0;
static uint32_t tim_compare[4] = {0, 0, 0, 0};
static uint32_t tim_flags = 0;
static uint32_t tim_it_status = 0;
static uint32_t tim_it_source = 0;
static bool tim_started = false;

// FLASH State
static uint32_t flash_flags = 0;
static uint32_t flash_it_status = 0;
static bool flash_locked = true;

// PWR State
static uint32_t pwr_flags = 0;
static uint32_t pwr_it_status = 0;

// EXTI State
static uint32_t exti_flags = 0;
static uint32_t exti_it_status = 0;
static uint32_t exti_enabled = 0;

// PCD State
static uint32_t pcd_flags = 0;
static uint32_t pcd_it_status = 0;

// Return status
static HAL_StatusTypeDef fake_return_status = HAL_OK;

// ============================================================================
// FAKE HAL CONTROL FUNCTIONS
// ============================================================================

static inline void fake_hal_reset_all(void) {
    rcc_flags = 0;
    rcc_it_status = 0;
    rcc_it_source = 0;
    gpio_output_state = 0;
    gpio_written_pin = 0;
    gpio_exti_flags = 0;
    gpio_exti_it_status = 0;
    gpio_exti_enabled = 0;
    dma_flags = 0;
    dma_it_status = 0;
    dma_it_source = 0;
    dma_transfer_complete = false;
    dma_src_addr = 0;
    dma_dst_addr = 0;
    dma_data_length = 0;
    tim_counter = 0;
    tim_autoreload = 0xFFFF;
    tim_prescaler = 0;
    memset(tim_compare, 0, sizeof(tim_compare));
    tim_flags = 0;
    tim_it_status = 0;
    tim_it_source = 0;
    tim_started = false;
    flash_flags = 0;
    flash_it_status = 0;
    flash_locked = true;
    pwr_flags = 0;
    pwr_it_status = 0;
    exti_flags = 0;
    exti_it_status = 0;
    exti_enabled = 0;
    pcd_flags = 0;
    pcd_it_status = 0;
    fake_return_status = HAL_OK;
}

static inline void fake_hal_set_return_status(HAL_StatusTypeDef status) {
    fake_return_status = status;
}

// ============================================================================
// RCC MACRO FUNCTIONS (same names as macros)
// ============================================================================

static inline uint32_t __HAL_RCC_GET_FLAG(uint32_t __FLAG__) {
    return (rcc_flags & __FLAG__) ? 1 : 0;
}

static inline void __HAL_RCC_CLEAR_FLAG(uint32_t __FLAG__) {
    rcc_flags &= ~__FLAG__;
}

static inline uint32_t __HAL_RCC_GET_IT_SOURCE(uint32_t __INTERRUPT__) {
    return (rcc_it_source & __INTERRUPT__) ? 1 : 0;
}

static inline uint32_t __HAL_RCC_GET_IT(uint32_t __INTERRUPT__) {
    return (rcc_it_status & __INTERRUPT__) ? 1 : 0;
}

static inline void __HAL_RCC_CLEAR_IT(uint32_t __INTERRUPT__) {
    rcc_it_status &= ~__INTERRUPT__;
}

// Test control
static inline void fake_hal_rcc_set_flag(uint32_t flag, uint32_t value) {
    if (value) {
        rcc_flags |= flag;
    } else {
        rcc_flags &= ~flag;
    }
}

static inline void fake_hal_rcc_set_it(uint32_t interrupt, uint32_t value) {
    if (value) {
        rcc_it_status |= interrupt;
    } else {
        rcc_it_status &= ~interrupt;
    }
}

// ============================================================================
// GPIO MACRO FUNCTIONS (same names as macros)
// ============================================================================

static inline uint32_t __HAL_GPIO_EXTI_GET_FLAG(uint32_t __EXTI_LINE__) {
    return (gpio_exti_flags & __EXTI_LINE__) ? 1 : 0;
}

static inline void __HAL_GPIO_EXTI_CLEAR_FLAG(uint32_t __EXTI_LINE__) {
    gpio_exti_flags &= ~__EXTI_LINE__;
}

static inline uint32_t __HAL_GPIO_EXTI_GET_IT(uint32_t __EXTI_LINE__) {
    return (gpio_exti_it_status & __EXTI_LINE__) ? 1 : 0;
}

static inline void __HAL_GPIO_EXTI_CLEAR_IT(uint32_t __EXTI_LINE__) {
    gpio_exti_it_status &= ~__EXTI_LINE__;
}

static inline void __HAL_GPIO_EXTI_ENABLE_IT(uint32_t __EXTI_LINE__) {
    gpio_exti_enabled |= __EXTI_LINE__;
}

static inline void __HAL_GPIO_EXTI_DISABLE_IT(uint32_t __EXTI_LINE__) {
    gpio_exti_enabled &= ~__EXTI_LINE__;
}

static inline void __HAL_GPIO_EXTI_ENABLE_RISING_IT(uint32_t __EXTI_LINE__) {
    gpio_exti_enabled |= (__EXTI_LINE__ << 16);
}

static inline void __HAL_GPIO_EXTI_ENABLE_FALLING_IT(uint32_t __EXTI_LINE__) {
    gpio_exti_enabled |= (__EXTI_LINE__ << 8);
}

// Test control
static inline void fake_hal_gpio_set_pin_state(uint16_t pin, GPIO_PinState state) {
    if (state == GPIO_PIN_SET) {
        gpio_output_state |= pin;
    } else {
        gpio_output_state &= ~pin;
    }
}

static inline GPIO_PinState fake_hal_gpio_get_pin_state(uint16_t pin) {
    return (gpio_output_state & pin) ? GPIO_PIN_SET : GPIO_PIN_RESET;
}

static inline uint16_t fake_hal_gpio_get_written_pin(void) {
    return gpio_written_pin;
}

// ============================================================================
// DMA MACRO FUNCTIONS (same names as macros)
// ============================================================================

static inline uint32_t __HAL_DMA_GET_FLAG(DMA_HandleTypeDef *__HANDLE__, uint32_t __FLAG__) {
    (void)__HANDLE__;
    return (dma_flags & __FLAG__) ? 1 : 0;
}

static inline void __HAL_DMA_CLEAR_FLAG(DMA_HandleTypeDef *__HANDLE__, uint32_t __FLAG__) {
    (void)__HANDLE__;
    dma_flags &= ~__FLAG__;
}

static inline uint32_t __HAL_DMA_GET_IT_SOURCE(DMA_HandleTypeDef *__HANDLE__, uint32_t __INTERRUPT__) {
    (void)__HANDLE__;
    return (dma_it_source & __INTERRUPT__) ? 1 : 0;
}

static inline void __HAL_DMA_ENABLE_IT(DMA_HandleTypeDef *__HANDLE__, uint32_t __INTERRUPT__) {
    (void)__HANDLE__;
    dma_it_source |= __INTERRUPT__;
}

static inline void __HAL_DMA_DISABLE_IT(DMA_HandleTypeDef *__HANDLE__, uint32_t __INTERRUPT__) {
    (void)__HANDLE__;
    dma_it_source &= ~__INTERRUPT__;
}

static inline uint32_t __HAL_DMA_GET_TC_FLAG_INDEX(DMA_HandleTypeDef *__HANDLE__) {
    (void)__HANDLE__;
    return DMA_FLAG_TC1;
}

static inline uint32_t __HAL_DMA_GET_HT_FLAG_INDEX(DMA_HandleTypeDef *__HANDLE__) {
    (void)__HANDLE__;
    return DMA_FLAG_HT1;
}

static inline uint32_t __HAL_DMA_GET_TE_FLAG_INDEX(DMA_HandleTypeDef *__HANDLE__) {
    (void)__HANDLE__;
    return DMA_FLAG_TE1;
}

static inline uint32_t __HAL_DMA_GET_FE_FLAG_INDEX(DMA_HandleTypeDef *__HANDLE__) {
    (void)__HANDLE__;
    return DMA_FLAG_FE1;
}

static inline uint32_t __HAL_DMA_GET_DME_FLAG_INDEX(DMA_HandleTypeDef *__HANDLE__) {
    (void)__HANDLE__;
    return DMA_FLAG_DME1;
}

// Test control
static inline void fake_hal_dma_set_flag(uint32_t flag, uint32_t value) {
    if (value) {
        dma_flags |= flag;
    } else {
        dma_flags &= ~flag;
    }
}

static inline void fake_hal_dma_set_transfer_complete(bool complete) {
    dma_transfer_complete = complete;
}

// ============================================================================
// TIM MACRO FUNCTIONS (same names as macros)
// ============================================================================

static inline void __HAL_TIM_ENABLE(TIM_HandleTypeDef *__HANDLE__) {
    (void)__HANDLE__;
    tim_started = true;
}

static inline void __HAL_TIM_DISABLE(TIM_HandleTypeDef *__HANDLE__) {
    (void)__HANDLE__;
    tim_started = false;
}

static inline uint32_t __HAL_TIM_GET_FLAG(TIM_HandleTypeDef *__HANDLE__, uint32_t __FLAG__) {
    (void)__HANDLE__;
    return (tim_flags & __FLAG__) ? 1 : 0;
}

static inline void __HAL_TIM_CLEAR_FLAG(TIM_HandleTypeDef *__HANDLE__, uint32_t __FLAG__) {
    (void)__HANDLE__;
    tim_flags &= ~__FLAG__;
}

static inline uint32_t __HAL_TIM_GET_IT_SOURCE(TIM_HandleTypeDef *__HANDLE__, uint32_t __INTERRUPT__) {
    (void)__HANDLE__;
    return (tim_it_source & __INTERRUPT__) ? 1 : 0;
}

static inline void __HAL_TIM_ENABLE_IT(TIM_HandleTypeDef *__HANDLE__, uint32_t __INTERRUPT__) {
    (void)__HANDLE__;
    tim_it_source |= __INTERRUPT__;
}

static inline void __HAL_TIM_DISABLE_IT(TIM_HandleTypeDef *__HANDLE__, uint32_t __INTERRUPT__) {
    (void)__HANDLE__;
    tim_it_source &= ~__INTERRUPT__;
}

static inline void __HAL_TIM_SET_COUNTER(TIM_HandleTypeDef *__HANDLE__, uint32_t counter_value) {
    (void)__HANDLE__;
    tim_counter = counter_value;
}

static inline uint32_t __HAL_TIM_GET_COUNTER(TIM_HandleTypeDef *__HANDLE__) {
    (void)__HANDLE__;
    return tim_counter;
}

static inline void __HAL_TIM_SET_AUTORELOAD(TIM_HandleTypeDef *__HANDLE__, uint32_t __AUTORELOAD__) {
    (void)__HANDLE__;
    tim_autoreload = __AUTORELOAD__;
}

static inline uint32_t __HAL_TIM_GET_AUTORELOAD(TIM_HandleTypeDef *__HANDLE__) {
    (void)__HANDLE__;
    return tim_autoreload;
}

static inline void __HAL_TIM_SET_PRESCALER(TIM_HandleTypeDef *__HANDLE__, uint32_t __PRESCALER__) {
    (void)__HANDLE__;
    tim_prescaler = __PRESCALER__;
}

static inline uint32_t __HAL_TIM_GET_PRESCALER(TIM_HandleTypeDef *__HANDLE__) {
    (void)__HANDLE__;
    return tim_prescaler;
}

static inline void __HAL_TIM_SET_COMPARE(TIM_HandleTypeDef *__HANDLE__, uint32_t __CHANNEL__, uint32_t __COMPARE__) {
    (void)__HANDLE__;
    if (__CHANNEL__ <= 3) {
        tim_compare[__CHANNEL__] = __COMPARE__;
    }
}

static inline uint32_t __HAL_TIM_GET_COMPARE(TIM_HandleTypeDef *__HANDLE__, uint32_t __CHANNEL__) {
    (void)__HANDLE__;
    if (__CHANNEL__ <= 3) {
        return tim_compare[__CHANNEL__];
    }
    return 0;
}

// Test control
static inline void fake_hal_tim_set_counter_value(uint32_t value) {
    tim_counter = value;
}

static inline void fake_hal_tim_set_flag(uint32_t flag, uint32_t value) {
    if (value) {
        tim_flags |= flag;
    } else {
        tim_flags &= ~flag;
    }
}

// ============================================================================
// FLASH MACRO FUNCTIONS (same names as macros)
// ============================================================================

static inline uint32_t __HAL_FLASH_GET_FLAG(uint32_t __FLAG__) {
    return (flash_flags & __FLAG__) ? 1 : 0;
}

static inline void __HAL_FLASH_CLEAR_FLAG(uint32_t __FLAG__) {
    flash_flags &= ~__FLAG__;
}

static inline uint32_t __HAL_FLASH_GET_IT_SOURCE(uint32_t __INTERRUPT__) {
    return (flash_it_status & __INTERRUPT__) ? 1 : 0;
}

static inline void __HAL_FLASH_ENABLE_IT(uint32_t __INTERRUPT__) {
    flash_it_status |= __INTERRUPT__;
}

static inline void __HAL_FLASH_DISABLE_IT(uint32_t __INTERRUPT__) {
    flash_it_status &= ~__INTERRUPT__;
}

// Test control
static inline void fake_hal_flash_set_flag(uint32_t flag, uint32_t value) {
    if (value) {
        flash_flags |= flag;
    } else {
        flash_flags &= ~flag;
    }
}

// ============================================================================
// PWR MACRO FUNCTIONS (same names as macros)
// ============================================================================

static inline uint32_t __HAL_PWR_GET_FLAG(uint32_t __FLAG__) {
    return (pwr_flags & __FLAG__) ? 1 : 0;
}

static inline void __HAL_PWR_CLEAR_FLAG(uint32_t __FLAG__) {
    pwr_flags &= ~__FLAG__;
}

static inline uint32_t __HAL_PWR_GET_IT_SOURCE(uint32_t __INTERRUPT__) {
    return (pwr_it_status & __INTERRUPT__) ? 1 : 0;
}

static inline void __HAL_PWR_ENABLE_IT(uint32_t __INTERRUPT__) {
    pwr_it_status |= __INTERRUPT__;
}

static inline void __HAL_PWR_DISABLE_IT(uint32_t __INTERRUPT__) {
    pwr_it_status &= ~__INTERRUPT__;
}

// Test control
static inline void fake_hal_pwr_set_flag(uint32_t flag, uint32_t value) {
    if (value) {
        pwr_flags |= flag;
    } else {
        pwr_flags &= ~flag;
    }
}

// ============================================================================
// EXTI MACRO FUNCTIONS (same names as macros)
// ============================================================================

static inline uint32_t __HAL_EXTI_GET_FLAG(uint32_t __EXTI_LINE__) {
    return (exti_flags & __EXTI_LINE__) ? 1 : 0;
}

static inline void __HAL_EXTI_CLEAR_FLAG(uint32_t __EXTI_LINE__) {
    exti_flags &= ~__EXTI_LINE__;
}

static inline uint32_t __HAL_EXTI_GET_IT(uint32_t __EXTI_LINE__) {
    return (exti_it_status & __EXTI_LINE__) ? 1 : 0;
}

static inline void __HAL_EXTI_CLEAR_IT(uint32_t __EXTI_LINE__) {
    exti_it_status &= ~__EXTI_LINE__;
}

static inline void __HAL_EXTI_ENABLE_IT(uint32_t __EXTI_LINE__) {
    exti_enabled |= __EXTI_LINE__;
}

static inline void __HAL_EXTI_DISABLE_IT(uint32_t __EXTI_LINE__) {
    exti_enabled &= ~__EXTI_LINE__;
}

static inline void __HAL_EXTI_ENABLE_RISING_IT(uint32_t __EXTI_LINE__) {
    exti_enabled |= (__EXTI_LINE__ << 16);
}

static inline void __HAL_EXTI_ENABLE_FALLING_IT(uint32_t __EXTI_LINE__) {
    exti_enabled |= (__EXTI_LINE__ << 8);
}

// Test control
static inline void fake_hal_exti_set_flag(uint32_t line, uint32_t value) {
    if (value) {
        exti_flags |= line;
    } else {
        exti_flags &= ~line;
    }
}

// ============================================================================
// PCD MACRO FUNCTIONS (same names as macros)
// ============================================================================

static inline uint32_t __HAL_PCD_GET_FLAG(PCD_HandleTypeDef *__HANDLE__, uint32_t __FLAG__) {
    (void)__HANDLE__;
    return (pcd_flags & __FLAG__) ? 1 : 0;
}

static inline void __HAL_PCD_CLEAR_FLAG(PCD_HandleTypeDef *__HANDLE__, uint32_t __FLAG__) {
    (void)__HANDLE__;
    pcd_flags &= ~__FLAG__;
}

static inline uint32_t __HAL_PCD_GET_IT_SOURCE(PCD_HandleTypeDef *__HANDLE__, uint32_t __INTERRUPT__) {
    (void)__HANDLE__;
    return (pcd_it_status & __INTERRUPT__) ? 1 : 0;
}

static inline void __HAL_PCD_ENABLE_IT(PCD_HandleTypeDef *__HANDLE__, uint32_t __INTERRUPT__) {
    (void)__HANDLE__;
    pcd_it_status |= __INTERRUPT__;
}

static inline void __HAL_PCD_DISABLE_IT(PCD_HandleTypeDef *__HANDLE__, uint32_t __INTERRUPT__) {
    (void)__HANDLE__;
    pcd_it_status &= ~__INTERRUPT__;
}

// ============================================================================
// GPIO HAL FUNCTIONS
// ============================================================================

static inline HAL_StatusTypeDef HAL_GPIO_Init(GPIO_TypeDef *GPIOx, GPIO_InitTypeDef *GPIO_Init) {
    (void)GPIOx;
    (void)GPIO_Init;
    return fake_return_status;
}

static inline void HAL_GPIO_DeInit(GPIO_TypeDef *GPIOx, uint32_t GPIO_Pin) {
    (void)GPIOx;
    (void)GPIO_Pin;
}

static inline GPIO_PinState HAL_GPIO_ReadPin(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin) {
    (void)GPIOx;
    return (gpio_output_state & GPIO_Pin) ? GPIO_PIN_SET : GPIO_PIN_RESET;
}

static inline void HAL_GPIO_WritePin(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, GPIO_PinState PinState) {
    (void)GPIOx;
    gpio_written_pin = GPIO_Pin;
    if (PinState == GPIO_PIN_SET) {
        gpio_output_state |= GPIO_Pin;
    } else {
        gpio_output_state &= ~GPIO_Pin;
    }
}

static inline void HAL_GPIO_TogglePin(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin) {
    (void)GPIOx;
    if (gpio_output_state & GPIO_Pin) {
        gpio_output_state &= ~GPIO_Pin;
    } else {
        gpio_output_state |= GPIO_Pin;
    }
}

static inline HAL_StatusTypeDef HAL_GPIO_LockPin(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin) {
    (void)GPIOx;
    (void)GPIO_Pin;
    return fake_return_status;
}

// ============================================================================
// RCC HAL FUNCTIONS
// ============================================================================

static inline HAL_StatusTypeDef HAL_RCC_OscConfig(RCC_OscInitTypeDef *RCC_OscInitStruct) {
    (void)RCC_OscInitStruct;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_RCC_ClockConfig(RCC_ClkInitTypeDef *RCC_ClkInitStruct, uint32_t FLatency) {
    (void)RCC_ClkInitStruct;
    (void)FLatency;
    return fake_return_status;
}

static inline uint32_t HAL_RCC_GetSysClockFreq(void) {
    return 16000000; // Default HSI frequency
}

static inline uint32_t HAL_RCC_GetHCLKFreq(void) {
    return 16000000;
}

static inline uint32_t HAL_RCC_GetPCLK1Freq(void) {
    return 16000000;
}

static inline uint32_t HAL_RCC_GetPCLK2Freq(void) {
    return 16000000;
}

// ============================================================================
// DMA HAL FUNCTIONS
// ============================================================================

static inline HAL_StatusTypeDef HAL_DMA_Init(DMA_HandleTypeDef *hdma) {
    (void)hdma;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_DMA_DeInit(DMA_HandleTypeDef *hdma) {
    (void)hdma;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_DMA_Start(DMA_HandleTypeDef *hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength) {
    (void)hdma;
    dma_src_addr = SrcAddress;
    dma_dst_addr = DstAddress;
    dma_data_length = DataLength;
    dma_transfer_complete = true;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_DMA_Start_IT(DMA_HandleTypeDef *hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength) {
    return HAL_DMA_Start(hdma, SrcAddress, DstAddress, DataLength);
}

static inline HAL_StatusTypeDef HAL_DMA_Abort(DMA_HandleTypeDef *hdma) {
    (void)hdma;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_DMA_PollForTransfer(DMA_HandleTypeDef *hdma, uint32_t CompleteLevel, uint32_t Timeout) {
    (void)hdma;
    (void)CompleteLevel;
    (void)Timeout;
    return dma_transfer_complete ? HAL_OK : HAL_TIMEOUT;
}

// ============================================================================
// TIM HAL FUNCTIONS
// ============================================================================

static inline HAL_StatusTypeDef HAL_TIM_Base_Init(TIM_HandleTypeDef *htim) {
    (void)htim;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_Base_DeInit(TIM_HandleTypeDef *htim) {
    (void)htim;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_Base_Start(TIM_HandleTypeDef *htim) {
    (void)htim;
    tim_started = true;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_Base_Stop(TIM_HandleTypeDef *htim) {
    (void)htim;
    tim_started = false;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_Base_Start_IT(TIM_HandleTypeDef *htim) {
    return HAL_TIM_Base_Start(htim);
}

static inline HAL_StatusTypeDef HAL_TIM_Base_Stop_IT(TIM_HandleTypeDef *htim) {
    return HAL_TIM_Base_Stop(htim);
}

static inline HAL_StatusTypeDef HAL_TIM_OC_Init(TIM_HandleTypeDef *htim) {
    (void)htim;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_OC_ConfigChannel(TIM_HandleTypeDef *htim, TIM_OC_InitTypeDef *sConfigOC, uint32_t Channel) {
    (void)htim;
    if (Channel <= 3) {
        tim_compare[Channel] = sConfigOC->Pulse;
    }
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_OC_Start(TIM_HandleTypeDef *htim, uint32_t Channel) {
    (void)htim;
    (void)Channel;
    tim_started = true;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_OC_Stop(TIM_HandleTypeDef *htim, uint32_t Channel) {
    (void)htim;
    (void)Channel;
    tim_started = false;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_PWM_Init(TIM_HandleTypeDef *htim) {
    (void)htim;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_PWM_ConfigChannel(TIM_HandleTypeDef *htim, TIM_OC_InitTypeDef *sConfigOC, uint32_t Channel) {
    return HAL_TIM_OC_ConfigChannel(htim, sConfigOC, Channel);
}

static inline HAL_StatusTypeDef HAL_TIM_PWM_Start(TIM_HandleTypeDef *htim, uint32_t Channel) {
    return HAL_TIM_OC_Start(htim, Channel);
}

static inline HAL_StatusTypeDef HAL_TIM_PWM_Stop(TIM_HandleTypeDef *htim, uint32_t Channel) {
    return HAL_TIM_OC_Stop(htim, Channel);
}

static inline HAL_StatusTypeDef HAL_TIM_IC_Init(TIM_HandleTypeDef *htim) {
    (void)htim;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_IC_ConfigChannel(TIM_HandleTypeDef *htim, TIM_IC_InitTypeDef *sConfigIC, uint32_t Channel) {
    (void)htim;
    (void)sConfigIC;
    (void)Channel;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_IC_Start(TIM_HandleTypeDef *htim, uint32_t Channel) {
    (void)htim;
    (void)Channel;
    tim_started = true;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_TIM_IC_Stop(TIM_HandleTypeDef *htim, uint32_t Channel) {
    (void)htim;
    (void)Channel;
    tim_started = false;
    return fake_return_status;
}

static inline uint32_t HAL_TIM_ReadCapturedValue(TIM_HandleTypeDef *htim, uint32_t Channel) {
    (void)htim;
    if (Channel <= 3) {
        return tim_compare[Channel];
    }
    return 0;
}

// ============================================================================
// FLASH HAL FUNCTIONS
// ============================================================================

static inline HAL_StatusTypeDef HAL_FLASH_Unlock(void) {
    flash_locked = false;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_FLASH_Lock(void) {
    flash_locked = true;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_FLASH_Program(uint32_t TypeProgram, uint32_t Address, uint64_t Data) {
    (void)TypeProgram;
    (void)Address;
    (void)Data;
    if (flash_locked) {
        return HAL_ERROR;
    }
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_FLASH_Program_IT(uint32_t TypeProgram, uint32_t Address, uint64_t Data) {
    return HAL_FLASH_Program(TypeProgram, Address, Data);
}

static inline HAL_StatusTypeDef HAL_FLASH_Erase_Sector(uint32_t Sector, uint32_t VoltageRange) {
    (void)Sector;
    (void)VoltageRange;
    if (flash_locked) {
        return HAL_ERROR;
    }
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_FLASH_Erase_Sector_IT(uint32_t Sector, uint32_t VoltageRange) {
    return HAL_FLASH_Erase_Sector(Sector, VoltageRange);
}

// ============================================================================
// EXTI HAL FUNCTIONS
// ============================================================================

static inline HAL_StatusTypeDef HAL_EXTI_Init(EXTI_HandleTypeDef *hexti) {
    exti_enabled |= hexti->Line;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_EXTI_DeInit(EXTI_HandleTypeDef *hexti) {
    exti_enabled &= ~hexti->Line;
    return fake_return_status;
}

static inline void HAL_EXTI_IRQHandler(EXTI_HandleTypeDef *hexti) {
    (void)hexti;
}

static inline void HAL_EXTI_Callback(EXTI_HandleTypeDef *hexti) {
    (void)hexti;
}

// ============================================================================
// PWR HAL FUNCTIONS
// ============================================================================

static inline HAL_StatusTypeDef HAL_PWR_ConfigBKPRegulator(uint32_t Regulator) {
    (void)Regulator;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_PWR_EnableBKPRegulator(void) {
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_PWR_DisableBKPRegulator(void) {
    return fake_return_status;
}

static inline void HAL_PWR_EnableWakeUpPin(uint32_t WakeUpPinPolarity) {
    (void)WakeUpPinPolarity;
}

static inline void HAL_PWR_DisableWakeUpPin(uint32_t WakeUpPin) {
    (void)WakeUpPin;
}

static inline HAL_StatusTypeDef HAL_PWR_EnterSTOPMode(uint32_t Regulator, uint8_t STOPEntry) {
    (void)Regulator;
    (void)STOPEntry;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_PWR_EnterSTANDBYMode(void) {
    return fake_return_status;
}

// ============================================================================
// PCD HAL FUNCTIONS
// ============================================================================

static inline HAL_StatusTypeDef HAL_PCD_Init(PCD_HandleTypeDef *hpcd) {
    (void)hpcd;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_PCD_DeInit(PCD_HandleTypeDef *hpcd) {
    (void)hpcd;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_PCD_Start(PCD_HandleTypeDef *hpcd) {
    (void)hpcd;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_PCD_Stop(PCD_HandleTypeDef *hpcd) {
    (void)hpcd;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_PCD_EP_Open(PCD_HandleTypeDef *hpcd, uint8_t ep_addr, uint16_t ep_mps, uint8_t ep_type) {
    (void)hpcd;
    (void)ep_addr;
    (void)ep_mps;
    (void)ep_type;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_PCD_EP_Close(PCD_HandleTypeDef *hpcd, uint8_t ep_addr) {
    (void)hpcd;
    (void)ep_addr;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_PCD_EP_Receive(PCD_HandleTypeDef *hpcd, uint8_t ep_addr, uint8_t *pBuf, uint32_t len) {
    (void)hpcd;
    (void)ep_addr;
    (void)pBuf;
    (void)len;
    return fake_return_status;
}

static inline HAL_StatusTypeDef HAL_PCD_EP_Transmit(PCD_HandleTypeDef *hpcd, uint8_t ep_addr, uint8_t *pBuf, uint32_t len) {
    (void)hpcd;
    (void)ep_addr;
    (void)pBuf;
    (void)len;
    return fake_return_status;
}


#endif /* FAKE_HAL_H */
